Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('cart',views.CartDetail.as_view(),name='Cart_datail'),
    path('cart/add/<int:pk>',views.CartAdd.as_view(),name='Cart_add')
]

Products/urls.py
from django.urls import path,re_path
from .import views

# نام اپ کاربران
app_name="Product"

urlpatterns = [
   re_path(r'products/(?P<slug>[-\w]+)/details',views.ProductDetails.as_view(), name='Product_details'),
   path('',views.Product_View.as_view(), name='Product_view'),
   path('product/list',views.Product_list.as_view(), name='Product_list'),
   

]

Shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('Products.urls')),
    path('', include('Cart.urls')),
    path('', include('Dashbord.urls')),
    path('', include('core.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .import views

# نام اپ کاربران
app_name="account"

urlpatterns = [
   path('login',views.UserLogin.as_view(), name='Login-user'),
   path('register',views.UserRegister.as_view(), name='Register-user'),
   path('verify',views.CheckOtp.as_view(), name='Verify'),
   path('logout', views.logout_user, name='logout'),
]

account/models.py
from datetime import timedelta
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import  AbstractBaseUser
from account.managment.managment import UserManager
from django.utils.translation import gettext as _
from  utils.validator import *
from django.core.validators import RegexValidator
from Products.models import *



class User(AbstractBaseUser):
    """User profile that authenticates and
    logs in with a phone number or email"""
    phone = models.CharField(
       verbose_name="شماره تلفن",
       max_length=255,
       unique=True,validators=[RegexValidator(regex=r'^09\d{9}$', message='شماره تلفن باید با 09 شروع شده و 11 رقم باشد')]
        )
    first_name = models.CharField(
        max_length=50,verbose_name='نام'
        )
    last_name = models.CharField(
        max_length=50, verbose_name='نام خانوادگی'
        )
    verification_time = models.DateField(
        verbose_name="تاریخ عضویت ",auto_now_add=True
        )
    is_active = models.BooleanField(
        default=True,verbose_name='فعال'
        )
    is_admin = models.BooleanField(
        verbose_name='وضعیت ادمین',default=False
        )
    email = models.EmailField(
        verbose_name= 'ایمیل',null=True,blank=True
        )
    image = models.ImageField(
        upload_to="profile/imag", null=True, blank=True,verbose_name='پروفایل'
        )
    password = models.CharField(
        max_length=300
        )
    national_code =models.CharField(
        validators=[persian_national_code,],null=True, blank=True,verbose_name='کد ملی' ,max_length=10
        )
    card_number = models.CharField(
        max_length=16, 
        validators=[RegexValidator(regex=r'^\d{16}$',
        message='شماره کارت باید 16 رقم باشد',
        code='invalid_card_number')],
        null=True, blank=True, verbose_name='شماره کارت')

    objects = UserManager()

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):

        return self.is_admin

    class  Meta:
        verbose_name = 'پروفایل'
        verbose_name_plural = 'پروفایل ها'



#ریجستر و احراز هویت شماره تلفن
class Otp(models.Model):
    """ Authentication related model
    with token creation feature
    """
    token = models.CharField(
        max_length=200, null=True, verbose_name='توکن'
        )
    phone = models.CharField(
    max_length=11,
    validators=[RegexValidator(regex=r'^09\d{9}$', message='شماره تلفن باید با 09 شروع شده و 11 رقم باشد')],
    verbose_name='شماره تلفن'
        )

    code = models.SmallIntegerField(
        verbose_name='کد یکبار مصرف'
        )
    code_expiry = models.DateTimeField(
        verbose_name='تاریخ انقضای کد',default=timezone.now() + timedelta(minutes=2),
        )
    is_used = models.BooleanField(
        default=False, verbose_name='استفاده شده؟'
        )
    
    
    class  Meta:
        verbose_name = 'رمز یکبار مصرف'
        verbose_name_plural = ' احراز هویت Otp'

    def is_valid(self, code):
        if self.code == code and not self.is_used and self.code_expiry:
            if timezone.now() <= self.code_expiry:
                return True
            else:
                self.delete()
                return False
        return False

    def set_code(self, code):
        self.code = code
        self.code_expiry = timezone.now() + timedelta(minutes=2)
        self.save()

    @classmethod
    def clean_expired_codes(cls):
        cls.objects.filter(models.Q(is_used=True) | models.Q(code_expiry__lt=timezone.now())).delete()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        User.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    
    

account/forms.py
import re
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from account.models import User , Otp




class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
    label="Password", widget=forms.PasswordInput
    )
    password2 = forms.CharField(
    label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ["phone", "last_name"]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("گذرواژه ها مطابقت ندارند")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    class Meta:
        model = User
        fields = ["phone", "password", "first_name","last_name", "is_active", "is_admin"]



class LoginForm(forms.Form):
    username = forms.CharField(
    widget=forms.TextInput(
    attrs={'class':'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center',
    "placeholder":"شماره همراه یا ایمیل "
    }))
    password = forms.CharField(
    widget=forms.PasswordInput(
    attrs={'class':'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'
    }))

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if not username:
           raise ValidationError("لطفاً ایمیل یا شماره همراه را وارد کنید.")

        phone_pattern = r"^09\d{9}$"
        email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"

        if re.match(phone_pattern, username):
            return username

        if re.match(email_pattern, username):
          return username

        raise ValidationError("فرمت وارد شده صحیح نیست. لطفاً ایمیل یا شماره همراه معتبر وارد کنید.")


    def clean_password(self):
        password = self.cleaned_data.get('password')

        if not password:
            raise ValidationError("رمز عبور الزامی است.")

        if len(password) < 8:
            raise ValidationError("رمز عبور باید حداقل ۸ کاراکتر باشد.")
        
        return password

    
   
class RegisterForm(forms.Form):
    first_name = forms.CharField (
    widget=forms.TextInput(
    attrs={'class': 'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'}
    ))
    last_name = forms.CharField (
    widget=forms.TextInput(
    attrs={'class': 'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'}),
    )
    phone = forms.CharField (
    widget=forms.TextInput(
    attrs={'class': 'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'}),
    min_length=11, max_length=11
    )
    password = forms.CharField (
    widget=forms.PasswordInput(
    attrs={'class': 'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'}),
    min_length=8, max_length=20
    )

    def clean_first_name (self):
        first_name = self.cleaned_data.get('first_name')

        if not first_name:
            raise ValidationError("لطفاً نام را وارد کنید.")

        if not re.match(r'^[آ-یa-zA-Z\s]+$', first_name):
            raise ValidationError("نام فقط می‌تواند شامل حروف باشد.")

        if len(first_name.strip().split()) < 1:
            raise ValidationError("نام معتبر نیست.")

        return first_name
 
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not last_name:
            raise ValidationError("لطفاً نام خانوادگی را وارد کنید.")

        if not re.match(r'^[آ-یa-zA-Z\s]+$', last_name):
            raise ValidationError("نام خانوادگی فقط می‌تواند شامل حروف باشد.")

        if len(last_name) < 3:
            raise ValidationError("نام خانوادگی باید حداقل 3 حرف باشد.")

        return last_name
 
    def clean_password(self):
        password = self.cleaned_data.get('password')

        if not password:
            raise ValidationError("رمز عبور الزامی است.")

        if len(password) < 8:
            raise ValidationError("رمز عبور باید حداقل ۸ کاراکتر باشد.")
        
        return password

 
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')

        if not phone.isdigit():
            raise ValidationError("شماره تلفن فقط باید شامل ارقام باشد.")

        if not phone.startswith("09"):
            raise ValidationError("شماره تلفن باید با 09 شروع شود.")

        return phone

   



class CheckOtpform(forms.ModelForm):
    code = forms.CharField(
    widget=forms.TextInput(
    attrs={'class': 'w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center'})
    ,max_length=4)

    def clean_code(self):
        code = self.cleaned_data.get('code')

        if not code:
            raise ValidationError("لطفاً کد تأیید را وارد کنید.")

        if not code.isdigit():
            raise ValidationError("کد باید فقط شامل ارقام باشد.")

        if len(code) != 4:
            raise ValidationError("کد باید دقیقاً ۴ رقم باشد.")

        return code
    
    class Meta:
        model = Otp
        fields = ['code']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        widget=forms.PasswordInput(
        attrs={'class': 'input_second input_all',
        'placeholder': 'رمز عبور فعلی'}
        )
    )
    new_password = forms.CharField(
        widget=forms.PasswordInput(
        attrs={'class': 'input_second input_all',
        'placeholder': 'رمز عبور جدید'}
        )
    )
    confirm_new_password = forms.CharField(
         widget=forms.PasswordInput(attrs={'class': 'input_second input_all', 'placeholder': 'تکرار رمز عبور جدید'}
        )
    )

    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        if len(new_password) < 8:
            raise ValidationError("رمز عبور باید حداقل 8 کاراکتر باشد.")
        if len(new_password) > 20:
            raise ValidationError("رمز عبور نباید بیشتر از 20 کاراکتر باشد.")
        return new_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_new_password = cleaned_data.get('confirm_new_password')

        if new_password and confirm_new_password and new_password != confirm_new_password:
            raise ValidationError("رمز عبور جدید و تکرار آن مطابقت ندارند.")
        return cleaned_data

account/views.py
from django.contrib.auth import authenticate , login, logout
from django.shortcuts import render , redirect
from django.views import View
from account.models import User,Otp
from .forms import LoginForm , CheckOtpform
from random import randint
from uuid import uuid4
from django.db import models
from django.shortcuts import render , redirect
from .forms import LoginForm,RegisterForm
from django.urls import reverse
import ghasedakpack
from uuid import uuid4
from django.views.generic import TemplateView
from django.contrib import messages


#Api  رمز یکبار مصرف
# sms_api = ghasedakpack.Ghasedak(
#   '6a061b6d44718f16ccf3e790fcb4d8c45957118c275c1983986285c820a5ca34i9sbhbmD3sdJnmyN')


class UserLogin(View):
    @staticmethod
    def get (request):
        form = LoginForm()
        return render(request,'login.html',{'form':form})

    def post(self,request):
        form = LoginForm(request.POST)
        if form.is_valid():
            valid = form.cleaned_data
            login_user = authenticate(username=valid['username'],password=valid['password'])
            if login_user is not None:
                login(request,login_user)
                return redirect('Product:Product_view')
            else:
                form.add_error("username", "اطلاعات وارد شده صحیح نمی باشد ")
        else:
            form.add_error("username","لطفا دوباره بررسی کنید اطلاعات وارد شده صحیح نمی باشد")

        return render(request,'login.html',{'form':form})
   
    
class UserRegister(View):
    """User login through phone number and email"""

    def get (self,request):
        form = RegisterForm()
        return render (request,'login-register.html',
         {'form':form})

    def post(self,request):
        phone = request.POST.get('phone')
        form = RegisterForm(request.POST)
        if form.is_valid():
          
            valid = form.cleaned_data
            randcode = randint(1000,9999)
            #دریافت رمز یکبار مصرف
            # sms_api.verification({
            #     'receptor':valid["phone"],'type':'1','template':'randcode','param1':randcode
            # })
            token = str(uuid4())

            Otp.objects.create(phone=valid['phone'],
                code=randcode,
                token=token
                )
            
            
            return redirect(reverse('account:Verify') + f'?token={token}')
        else:
                form.add_error('phone', "اطلاعات وارد شده صحیح نمی باشد ")
        return render(request,"verify.html",{'form':form,'phone': phone})


class CheckOtp(View):
    """
    To authenticate the entered number and expire
    the one-time code within 2 minutes
    """

    def get(self, request):
        form = CheckOtpform()
        return render(request, 'verify.html',
            {'form': form })

    def post(self,request):
        token = request.GET.get('token')
        form = CheckOtpform(request.POST)

        if form.is_valid():
            valid = form.cleaned_data

            if Otp.objects.filter(code=valid['code'],
              token=token,
            ).exists():
             otp = Otp.objects.get(token=token)

             if otp.is_expired:
                    form.add_error('code', "کد منقضی شده است")
                    return render(request, 'verify.html', {'form': form})
             user , is_created = User.objects.get_or_create(phone=otp.phone,)
             
             User.objects.create_user(
                phone=form.cleaned_data.get('phone'),
                last_name=form.cleaned_data.get('last_name'),
                first_name=form.cleaned_data.get('first_name'),
                password=form.cleaned_data.get('password')
                )

             login(request,
                   user,
                   backend="django.contrib.auth.backends.ModelBackend")
             return redirect('/')

            otp.delete()

        else:
            form.add_error(None, "اطلاعات وارد شده صحیح نمی باشد ")

        return render(request,'verify.html',{'form':form })


def logout_user(request):
    logout(request)
    return redirect('/')

account/templates/login-register.html
 {% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ثبت نام</title>

  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">
  <style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
  </style>
</head>
<body class="bg-gray-50">
  <div class="flex justify-center items-center text-right h-screen w-96 mx-auto">
    <div class="shadow-xl rounded-2xl p-8 bg-white">
      <form method="POST" action="?phone={{ request.GET.phone }}">
        {% csrf_token %}

        <div class="mb-2">
          <a href="{% url 'Product:Product_view' %}">
            <img src="{% static 'image/logo.png' %}" alt="" class="w-36 mx-auto">
          </a>
        </div>
        <div class="opacity-80 text-lg mb-5">
            ثبت نام
        </div>
         <div class="text-xs opacity-70 mb-2">
          نام :
        </div>
        <div class="mb-2">

          {{form.first_name}}

        </div>
         <div class="text-xs opacity-70 mb-2">
          نام خانوادگی :
        </div>
        <div class="mb-2">

          {{form.last_name}}

        </div>
        <div class="text-xs opacity-70 mb-2">
          شماره همراه :
        </div>
        <div class="mb-2">

          {{form.phone}}

        </div>
         <div class="text-xs opacity-70 mb-2">
          گذرواژه :
        </div>
        <div class="mb-2">

          {{form.password}}

        </div>
           <div class="text-xs text-red-500 hidden">
        </div>
        <div class="text-center mt-5 mb-3">
          <button class="bg-red-500 hover:bg-red-600 transition text-white opacity-80 rounded-2xl w-full py-2" type="submit">
            ثبت نام
          </button>
        </div>
        <div class="text-xs opacity-80">
          ثبت نام یا ورود شما به منظور پذیرش
          <a href="#" class="text-red-500">قوانین و مقررات</a>
          ایران مارکت می باشد
        </div>
      </form>
    </div>
  </div>
</body>
</html>

account/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>

  {% if messages %}
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      {
        %
        for message in messages %
      }
      Swal.fire({
        icon: 'success',
        title: 'موفق!',
        text: '{{ message|escapejs }}',
        confirmButtonText: 'بستن',
        customClass: {
          popup: 'rounded-xl p-6 shadow-lg',
          confirmButton: 'bg-green-600 text-white px-4 py-2 rounded-md hover:bg-red-700'
        }
      }); {
        % endfor %
      }
    });
  </script>
  {% endif %}

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ورود</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">
  <style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
  </style>
</head>

<body class="bg-gray-50">
  <div class="flex justify-center items-center text-right h-screen w-96 mx-auto">
    <div class="shadow-xl rounded-2xl p-8 bg-white">
      <form method="post">
        {% csrf_token %}
        <div class="mb-2">
          <a href="{% url 'Product:Product_view' %}">
            <img src="{% static 'image/logo.png' %}" alt="" class="w-36 mx-auto">
          </a>
        </div>
        <div class="opacity-80 text-lg mb-5">
          ورود
        </div>
        <div class="text-xs opacity-70 mb-2">
          شماره همراه یا ایمیل خود را وارد کنید:
        </div>
        <div class="mb-2">

          {% for error in form.username.errors %}
          <p class="alert alert-danger">{{ error }}</p>
          {% endfor %}
          {{ form.username }}

        </div>
        <div class="text-xs opacity-70 mb-2">
          رمز عبور
        </div>

        <div class="mb-2">
          {{ form.password }}
        </div>

        <div class="text-center mt-5 mb-3">
          <button class="bg-red-500 hover:bg-red-600 transition text-white opacity-80 rounded-2xl w-full py-2"
            type="submit">
            ورود
          </button>
        </div>
        <div class="text-xs opacity-80">
          ثبت نام یا ورود شما به منظور پذیرش
          <a href="#" class="text-red-500">قوانین و مقررات</a>
          فروشگاه می باشد
        </div>
      </form>
    </div>
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</html>

account/templates/password-change.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>تغییر رمز عبور</title>

  <link rel="stylesheet" href="./assets/css/output.css" />
  <link rel="stylesheet" href="./assets/css/font.css">
  <style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
  </style>
</head>
<body class="bg-gray-50">
  <div class="flex justify-center items-center text-right h-screen w-96 mx-auto">
    <div class="shadow-xl rounded-2xl p-8 bg-white">
      <form action="">
        <div class="mb-2">
          <a href="./index.html">
            <img src="./assets/image/logo.png" alt="" class="w-36 mx-auto">
          </a>
        </div>
        <div class="opacity-80 text-lg mt-3 mb-5">
          تغییر رمز عبور
        </div>
        <div class="text-xs opacity-70 mt-5 mb-2">
          کد ارسال شده به شماره 09123456789 را وارد کنید:
        </div>
        <div class="mb-2">
          <div class="input-field mb-5 flex flex-row-reverse gap-x-4 justify-center">
            <input type="number" class="inputVerify w-10 h-11 rounded-md outline-none text-center drop-shadow-lg"/>
            <input type="number" class="inputVerify w-10 h-11 rounded-md outline-none text-center drop-shadow-lg" disabled />
            <input type="number" class="inputVerify w-10 h-11 rounded-md outline-none text-center drop-shadow-lg" disabled />
            <input type="number" class="inputVerify w-10 h-11 rounded-md outline-none text-center drop-shadow-lg" disabled />
          </div>
        </div>
        <div class="text-xs opacity-70 mb-2">
          رمز عبور جدید
        </div>
        <div class="mb-2">
          <input class="w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center" type="text">
        </div>
        <div class="text-xs opacity-70 mb-2">
          تکرار رمز عبور جدید
        </div>
        <div class="mb-2">
          <input class="w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center" type="text">
        </div>
        <div class="text-xs text-red-500 hidden">
          شماره موبایل نادرست است
        </div>
        <div class="text-center mt-5 mb-3">
          <button class="bg-red-500 hover:bg-red-600 transition text-white opacity-80 rounded-2xl w-full py-2" type="submit">
            تغییر رمز عبور
          </button>
        </div>
        <div class="text-xs opacity-80">
          ثبت نام یا ورود شما به منظور پذیرش
          <a href="#" class="text-red-500">قوانین و مقررات</a>
          ایران مارکت می باشد
        </div>
      </form>
    </div>
  </div>
</body>
<script src="./assets/js/main.js"></script>
<script src="./assets/js/verifyUser.js"></script>
</html>

account/templates/password-forget.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>تغییر رمز عبور</title>

  <link rel="stylesheet" href="./assets/css/output.css" />
  <link rel="stylesheet" href="./assets/css/font.css">
  <style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
  </style>
</head>
<body class="bg-gray-50">
  <div class="flex justify-center items-center text-right h-screen w-96 mx-auto">
    <div class="shadow-xl rounded-2xl p-8 bg-white">
      <form action="">
        <div class="mb-2">
          <a href="./index.html">
            <img src="./assets/image/logo.png" alt="" class="w-36 mx-auto">
          </a>
        </div>
        <div class="opacity-80 text-lg mb-5">
          فراموشی گذرواژه
        </div>
        <div class="text-xs opacity-70 mb-2">
          شماره همراه یا ایمیل خود را وارد کنید:
        </div>
        <div class="mb-2">
          <input class="w-full drop-shadow-lg outline-none rounded-2xl py-2 text-center" type="text">
        </div>
        <div class="text-xs text-red-500 hidden">
          شماره موبایل نادرست است
        </div>
        <div class="text-center mt-5 mb-3">
          <button class="bg-red-500 hover:bg-red-600 transition text-white opacity-80 rounded-2xl w-full py-2" type="submit">
            بازگردانی رمز عبور
          </button>
        </div>
        <div class="text-xs opacity-80">
          ثبت نام یا ورود شما به منظور پذیرش
          <a href="#" class="text-red-500">قوانین و مقررات</a>
          ایران مارکت می باشد
        </div>
      </form>
    </div>
  </div>
</body>
</html>

account/templates/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>خوش آمدید</title>

  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">

</head>
<body class="bg-gray-50">
  <div class="flex justify-center items-center text-right h-screen w-96 mx-auto">
    <div class="shadow-xl rounded-2xl p-8 bg-white">
      <form action="">
        <div class="mb-2">
          <a href="{% url 'Product:Product_view' %}">
            <img src="{{ site_settings.logo.url }}" alt="" class="w-36 mx-auto">
          </a>
        </div>
        <div class="opacity-80 text-lg my-5 text-center">
           به ایران مارکت خوش آمدید
        </div>
        <div class="text-xs text-center opacity-70 mb-2">
           برای دسترسی کامل ابتدا وارد حساب کاربری خود شوید
        </div>
        <div class="text-center mt-5 mb-3">
          <button 
          type="button"
          onclick="window.location.href='{% url 'account:Login-user' %}'"
          class="bg-red-500 hover:bg-red-600 transition text-white opacity-80 rounded-2xl w-full py-2 mb-5">
            تکمیل حساب کاربری
          </button>
          <div class="flex justify-center items-center">
            <a class="border-b-2 border-red-500 hover:text-red-600 transition" href="{% url 'Product:Product_view' %}">
              صفحه اصلی
            </a>
            <img class="w-5" src="{% static 'image/arrow-left.png' %}" alt="">
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/verifyUser.js' %}"></script>
</html>