Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('cart',views.CartDetail.as_view(),name='Cart_datail'),
    path('cart/add/<int:pk>',views.CartAdd.as_view(),name='Cart_add')
]

Dashbord/urls.py
from django.urls import path
from . import views

app_name = 'Profile'

urlpatterns = [
    path('profile/view',views.UserProfile,name='Profile_View'),
    path('profile/address',views.AddressView.as_view(),name='Address'),
    path('profile/address/add',views.Address_Add.as_view(),name='Address_add'),
    path('profile/change',views.Change_profile,name='ChangeProfile'),
    path('profile/change/password',views.ChangePasswordView.as_view(),name='ChangePassword'),
    path('profile/notifications',views.NotificationList.as_view(),name='Notification'),
    path('profile/comment',views.CommentViews.as_view(),name='CommentViews'),
    path('profile/comment/delete/<int:comment_id>/',views.DeleteCommentView.as_view(),name='DeleteCommentView'),
    path('profile/favorite',views.FavoriteViews.as_view(),name='FavoriteViews'),
    
]
    

Products/urls.py
from django.urls import path,re_path
from .import views

# نام اپ کاربران
app_name="Product"

urlpatterns = [
   re_path(r'products/(?P<slug>[-\w]+)/details',views.ProductDetails.as_view(), name='Product_details'),
   path('',views.Product_View.as_view(), name='Product_view'),
   path('product/list',views.Product_list.as_view(), name='Product_list'),
   

]

Shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('Products.urls')),
    path('', include('Cart.urls')),
    path('', include('Dashbord.urls')),
    path('', include('core.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashbord/forms.py
from django import forms
from .models import Address
from django.core.exceptions import ValidationError
from django.contrib import messages
from account.models import User


class AddressAdd(forms.ModelForm):
    user = forms.IntegerField(
        required=False
        )

    class Meta:
     model = Address
     fields = ('title','first_name','last_name','phone_number','city','province','postal_code','full_address','is_default','email',)
   
     widgets = {
            'title': forms.TextInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "محل کار , منزل..."
            }),
            'first_name': forms.TextInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            " نام و نام خانوادگی تحویل گیرنده"
            }),
            'last_name': forms.TextInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            " نام و نام خانوادگی تحویل گیرنده"
            }),
            'phone_number': forms.NumberInput(
            attrs={
            'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "شماره همراه تحویل گیرنده"
            }),
            'city': forms.TextInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "استان"
            }),
            'province': forms.TextInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "شهرستان"
            }),
            'postal_code': forms.NumberInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "کدپستی"
            }),
            'email': forms.EmailInput(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "ایمیل را وارد کنید (الزامی نیست)"
            }),
            'full_address': forms.Textarea(
            attrs={'class':
            "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300",
            "placeholder":
            "آدرس کامل"}
            ),
            'is_default': forms.CheckboxInput(
            attrs={'class':
            "form-checkbox h-5 w-5 text-blue-600 focus:ring-blue-500 cursor-pointer mr-1",
            })}


    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 3:
            raise ValidationError("عنوان آدرس باید حداقل 3 کاراکتر باشد.")
        if len(title) > 30:
            raise ValidationError("عنوان آدرس باید حداکثر 30 کاراکتر باشد.")
        return title

    def clean_full_address(self):
        full_address = self.cleaned_data.get('full_address')
        if len(full_address) < 10:
            raise ValidationError("آدرس باید حداقل 10 کاراکتر باشد.")
        if len(full_address) > 300:
            raise ValidationError("آدرس باید حداکثر 300 کاراکتر باشد.")
        return full_address

    def clean_city(self):
        city = self.cleaned_data.get('city')
        if len(city) < 2:
            raise ValidationError("استان باید حداقل 2 کاراکتر باشد.")
        if len(city) > 50:
            raise ValidationError("استان باید حداکثر 50 کاراکتر باشد.")
        return city

    def clean_province(self):
        province = self.cleaned_data.get('province')
        if len(province) < 2:
            raise ValidationError("شهرستان باید حداقل 2 کاراکتر باشد.")
        if len(province) > 50:
            raise ValidationError("شهرستان باید حداکثر 50 کاراکتر باشد.")
        return province
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if len(first_name) < 3:
            raise ValidationError("نام باید حداقل  3 کاراکتر باشد .")
        if len(first_name) > 50:
            raise ValidationError("نام باید حداکثر 50 کاراکتر باشد.")
        return first_name 
    
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if len(last_name) < 3:
            raise ValidationError("نام خانوداگی باید حداقل  3 کاراکتر باشد .")
        if len(last_name) > 50:
            raise ValidationError("نام خانوداگی باید حداکثر 50 کاراکتر باشد.")
        return last_name

    def clean_postal_code(self):
        postal_code = self.cleaned_data.get('postal_code')
        if len(postal_code) != 10:
            raise ValidationError("کد پستی باید 10 رقم باشد.")
        if not postal_code.isdigit():
            raise ValidationError("کد پستی باید فقط شامل اعداد باشد.")
        return postal_code

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if not phone_number.startswith('09'):
            raise ValidationError("شماره تلفن باید با 09 شروع شود.")
        if len(phone_number) != 11:
            raise ValidationError("شماره تلفن باید 11 رقم باشد.")
        return phone_number

    def clean_receiver_name(self):
        receiver_name = self.cleaned_data.get('receiver_name')
        if len(receiver_name.split()) < 2:
            raise ValidationError("لطفا نام و نام خانوادگی تحویل گیرنده را وارد کنید.")
        return receiver_name
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email is None:
            email = ''
        if email:
            if not email.endswith('@gmail.com'):
                raise ValidationError("لطفاً یک ایمیل معتبر با دامنه @gmail.com وارد کنید.")
            if len(email) < 15:
                raise ValidationError("ایمیل باید حداقل 15 کاراکتر باشد.")
            if len(email) > 100:
                raise ValidationError("ایمیل باید حداکثر 100 کاراکتر باشد.")
        return email

    
class Change_Profile(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('phone','first_name','last_name','email','national_code','card_number','image')
        
    phone = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    first_name = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    last_name = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    email = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    national_code = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    card_number = forms.CharField(
    required=False,
    widget=forms.TextInput(attrs={
    'class': "text-sm block w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal text-gray-700 outline-none focus:border-red-300"
    }))
 
    image = forms.ImageField(
    required=False,
    widget=forms.ClearableFileInput(attrs={
    'class': 'hidden',
    'accept': 'image/*',
    'id': 'dropzone-file',
    }))
 
       
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name is None:
            first_name = ''
        if len(first_name) > 50:
            raise ValidationError("نام باید حداکثر 50 کاراکتر باشد.")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name is None:
            last_name = ''
        if len(last_name) > 100:
            raise ValidationError("نام خانوادگی باید حداکثر 100 کاراکتر باشد.")
        return last_name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email is None:
            email = ''
        if email:
            if not email.endswith('@gmail.com'):
                raise ValidationError("لطفاً یک ایمیل معتبر با دامنه @gmail.com وارد کنید.")
            if len(email) < 15:
                raise ValidationError("ایمیل باید حداقل 15 کاراکتر باشد.")
            if len(email) > 100:
                raise ValidationError("ایمیل باید حداکثر 100 کاراکتر باشد.")
        return email

   
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone is None:
            phone = ''
        if phone:
            if not phone.startswith('09'):
                raise ValidationError("شماره تلفن باید با 09 شروع شود.")
            if len(phone) != 11:
                raise ValidationError("شماره تلفن باید 11 رقم باشد.")

Dashbord/views.py
from django.contrib.auth import  logout
from pyexpat.errors import messages
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render,redirect
from django.views.generic import ListView,View,TemplateView
from .forms import AddressAdd, Change_Password,Change_Profile
from .models import *
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from Products.models import Comment


@login_required
def UserProfile(request):
    user = request.user
    context = {
        'profile': user,
    }
    return render(request, 'profile/profile.html', context)


@login_required
def Change_profile(request):
    user = request.user
    form = Change_Profile(instance=user)
    if request.method == 'POST':
        form = Change_Profile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'اطلاعات با موفقیت ویرایش شد.')
            print(type(request))
            return redirect('Profile:Profile_View')
    return render(request , "profile/profile-change.html",{"form": form})


class NotificationList(LoginRequiredMixin,View):
  
   def get(self,request): 
    user = request.user
    
    Notification.delete_expired_notifications()

    now = timezone.now()
    notifications = Notification.objects.filter(
        is_active=True
    ).filter(
        Q(is_for_all_users=True) | Q(users=user)
    ).filter(
        Q(expiration_date__isnull=True) | Q(expiration_date__gte=now)
    ).distinct().order_by('-created_at')

   
    return render(request, 'profile/notification.html', {
        'notifications': notifications,
    })


class AddressView(LoginRequiredMixin,ListView):
    template_name = 'profile/profile-address.html'
    model = Address
    context_object_name = 'Address'
    
    def post(self, request):
        user = request.user

        if 'delete_address' in request.POST:
            address_id = request.POST.get('delete_address')
            address = get_object_or_404(Address, pk=address_id, user=user)
            address.delete()

        elif 'set_default' in request.POST:
            address_id = request.POST.get('set_default')
            address = get_object_or_404(Address, pk=address_id, user=user)
            
            Address.objects.filter(user=user, is_default=True).update(is_default=False)

            address.is_default = True
            address.save()
           
        return redirect(
            'Profile:Address'
            )
        
        
class Address_Add(LoginRequiredMixin,View):
    
    def post(self,request):
        user = request.user
        if Address.objects.filter(user=user).count() >= 3:
            messages.error(request, 'شما فقط می‌توانید ۳ آدرس ثبت کنید.')
            return redirect('Profile:Address')
        
        form = AddressAdd(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            
            address.save()
            
            return redirect('Profile:Address') 
        else:      
            return render (request,'profile/profile-address-edit.html',{'form':form})
        
    def get (self,request):
        form = AddressAdd()
        return render (request,'profile/profile-address-edit.html',{
            'form':form
            })
     
class ChangePasswordView(LoginRequiredMixin, FormView):
    
    template_name = 'profile/change-password.html'
    form_class = Change_Password
    success_url = reverse_lazy('account:Login-user')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        old_password = form.cleaned_data['old_password']
        new_password = form.cleaned_data['new_password']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(self.request, user)
            logout(self.request)
            messages.success(self.request, 'رمز عبور شما با موفقیت تغییر یافت. لطفاً با رمز عبور جدید وارد شوید.')
            return super().form_valid(form)
        
        else:
            form.add_error('old_password', 'رمز عبور فعلی نادرست است.')
            return self.form_invalid(form)


class CommentViews(ListView):
    
    model = Comment
    template_name = 'profile/profile-comments.html'
    context_object_name = 'comments'
    paginate_by = 4
    
    def get_queryset(self):
        return Comment.objects.filter(user=self.request.user, parent__isnull=True).order_by('-created_at')
    
class DeleteCommentView(View):
    
    def get(self,request, *args, **kwargs):
        comment_id = kwargs.get('comment_id')
        comment = get_object_or_404(Comment,pk=comment_id,user=request.user)
        comment.delete()
        return redirect('Profile:CommentViews')
        


class FavoriteViews(ListView):
    
    model = Favorites
    template_name = 'profile\profile-favorites.html'
    context_object_name = 'favorites'
    paginate_by = 4
    
    def get_queryset(self):
        return Favorites.objects.filter(user=self.request.user).order_by('-created_at')

    

Dashbord/templates/profile/notification.html
{% load static %}
{% load jalali_tags %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>آدرس های من</title>

  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">

</head>

<body class="bg-gray-50">
  <!-- NAVBAR -->
  <div>
    <!-- TOP -->
    {% include 'includes/head.html' %}
    <!-- OPACITY SCREEN FOR SEARCH INPUT FOCUS -->
    <div class="absolute w-full h-screen bg-gray-200 opacity-40 z-40 hidden" id="opacitiScreen" onclick="closeScreen()">
    </div>
  </div>

  <!-- MAIN -->
{% include 'includes/profile_navbar.html' %}

  {% if notifications %}
    {% for notification in notifications %}

  <div class="md:w-8/12 lg:w-9/12 flex flex-col gap-y-5">
    <div class="border rounded-3xl shadow-lg flex flex-col p-5 gap-y-5">
      <div class="mb-4">

        <div class="opacity-80">
          {{ notification.message }}
        </div>
      </div>

      <div class="md:grid grid-cols-2">
        <div>
          <div class="text-xs sm:text-sm md:text-base lg:text-lg font-bold text-green-600 mb-1" style="color: #16a34a;">
            تاریخ ایجاد:
          </div>
          <div class="text-sm opacity-90">
            {{ notification.created_at|to_jalali:'%d %b %Y' }}
          </div>
        </div>

        <div>
          {% if notification.expiration_date %}
          <div class="text-xs sm:text-sm md:text-base lg:text-lg font-bold text-green-600 mb-1" style="color: #ee2626ff;">
            اعتبار تا :
          </div>
          <div class="text-sm opacity-90">
            {{ notification.expiration_date|to_jalali:'%d %b %Y' }}
          </div>
          {% endif %}
        </div>
      </div>

      {% endfor %}
        {% else %}

      <div class="md:w-8/12 lg:w-9/12 flex flex-col gap-y-5">
    <div class="border rounded-3xl shadow-lg flex flex-col p-5 gap-y-5">
      <div>
        <div class="opacity-80">
          <div
            class="bg-gradient-to-r from-purple-100 via-pink-100 to-red-100 border border-red-200 rounded-2xl p-4 text-center shadow-md">
            <p class="text-sm md:text-base text-gray-700 font-medium">
              وقتی اتفاق جدیدی بیفته، اینجا بهت خبر می‌دیم.
             

            </p>
          </div>
        </div>
      </div>

          {% endif %}

        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  </div>

  <!-- FOOTER -->
  {% include 'includes/footer.html' %}
</body>
<!--DROPDOWNS FOR NAVBAR-->
<script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer>
</script>
<!--MOBILE NAVBAR-->
<script src="{% static 'js/navbar.js' %}"></script>
<!-- SHOW MODAL SEARCH -->
<script src="{% static 'js/searchBox.js' %}"></script>

</html>

Dashbord/templates/profile/profile-comments.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>نظرات من</title>

  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">

  <!-- animate.css-->
  <style>
    .swal2-styled {
      color: black !important;
    }
  </style>

</head>

<body class="bg-gray-50">
  <!-- NAVBAR -->
  <div>
    <!-- TOP -->
    {% include 'includes/head.html' %}
    <!-- OPACITY SCREEN FOR SEARCH INPUT FOCUS -->
    <div class="absolute w-full h-screen bg-gray-200 opacity-40 z-40 hidden" id="opacitiScreen" onclick="closeScreen()">
    </div>
  </div>
  <!-- MAIN -->
  {% include 'includes/profile_navbar.html' %}

  {% if not comments %}

  <div class="md:w-8/12 lg:w-9/12 flex flex-col gap-y-5">
    <div class="border rounded-3xl shadow-lg flex flex-col p-5 gap-y-5">
      <div>
        <div class="opacity-80">
          <div class="bg-gradient-to-r from-purple-100 via-pink-100 to-red-100 border border-red-200 rounded-2xl p-4 text-center shadow-md">
  <p class="text-sm md:text-base text-gray-700 font-medium">
    نظرت برای ما مهمه—
    <span class="text-red-500 font-semibold"> تجربه‌ت رو با دیگران به اشتراک بذار</span>
    رو اینجا ذخیره کن.
  </p>
</div>
        </div>
      </div>

      {% else %}

      <div class="md:w-8/12 lg:w-9/12 flex flex-col gap-y-5">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500">
          <thead class="hidden md:table-header-group text-xs text-gray-700 bg-gray-50">
            <tr>
              <th scope="col" class="py-3">
                <span class="sr-only">تصویر</span>
              </th>
              <th scope="col" class="md:pr-6 py-3">
                نام محصول
              </th>
              <th scope="col" class="pr-5 py-3">
                نظر
              </th>
              <th scope="col" class="px-6 py-3">
                وضعیت
              </th>
              <th scope="col" class="px-3 py-3">
                عملیات
              </th>
            </tr>
          </thead>
         
          {% for comment in comments %}
          <tbody class="grid grid-cols-1 sm:grid-cols-2 md:contents gap-5">
            <tr
              class="bg-white hover:bg-gray-50 grid grid-cols-1 justify-items-center md:table-row border-x sm:border-x-0 sm:border-b">
              <td class="px-2 py-4">
                <img src="{{ comment.products.image.url }}" class="w-48 md:w-28 max-w-full max-h-full rounded-lg"
                  alt="">
              </td>
              <td class="md:pr-6 py-4 text-xs opacity-90 text-gray-900">
                <a href="{% url 'Product:Product_details' comment.products.id %}" class="hover:underline text-blue-600">
                  {{ comment.products.title }}
                </a>
              </td>
              <td class="px-3 py-4 max-w-md text-xs">
                {{ comment.body|truncatechars:20 }}
              </td>
              {% if comment.status == 'It was confirmed' %}
              <td class="px-6 py-4 text-sm opacity-90 text-green-500">
                تایید شده
              </td>
              {% elif comment.status == 'Awaiting confirmation' %}
              <td class="px-6 py-4 text-sm opacity-90 text-yellow-500">
                در انتظار تایید
              </td>
              {% else %}
              <td class="px-6 py-4 text-sm opacity-90 text-red-500">
                ردشده
              </td>
              {% endif %}
              <td class="px-3 py-4">
                <a href="{% url 'Profile:DeleteCommentView' comment.id %}"
                  class="text-red-600 hover:underline delete-comment"
                  data-url="{% url 'Profile:DeleteCommentView' comment.id %}">
                  حذف
                </a>
              </td>
            </tr>
          {% endfor %}
            {% endif %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  </div>
  <div class="mb-10">
    <ul class="flex items-center justify-center gap-x-2 md:gap-x-3 h-8 text-sm">
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 ms-0 text-gray-500 bg-white rounded-lg hover:bg-gray-100">
          <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
          </svg>
        </a>
      </li>
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 text-red-600  bg-red-200 rounded-lg hover:bg-gray-100">1</a>
      </li>
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 text-gray-500 bg-white rounded-lg hover:bg-gray-100">2</a>
      </li>
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 rounded-lg text-gray-500 bg-white hover:bg-gray-100">3</a>
      </li>
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 text-gray-500 bg-white rounded-lg hover:bg-gray-100">...</a>
      </li>
       <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 text-gray-500 bg-white rounded-lg hover:bg-gray-100">8</a>
      </li>
      <li>
        <a href="#" class="flex items-center justify-center transition shadow-lg px-3 h-8 text-gray-500 bg-white rounded-lg hover:bg-gray-100">
          <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
  <!-- FOOTER -->
  {% include 'includes/footer.html' %}
</body>
<!--DROPDOWNS FOR NAVBAR-->
<script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer>
</script>
<!--MOBILE NAVBAR-->
<script src="{% static 'js/navbar.js' %}"></script>
<!-- SHOW MODAL SEARCH -->
<script src="{% static 'js/searchBox.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const deleteLinks = document.querySelectorAll('.delete-comment');
    deleteLinks.forEach(link => {
      link.addEventListener('click', function(e) {
        e.preventDefault(); // جلوگیری از رفتن مستقیم به لینک
        const url = this.getAttribute('data-url');
        Swal.fire({
          title: 'آیا مطمئن هستید؟',
          text: "این نظر برای همیشه حذف خواهد شد!",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#d33',
          cancelButtonColor: '#3085d6',
          confirmButtonText: 'بله، حذف شود!',
          cancelButtonText: 'لغو'
        }).then((result) => {
          if (result.isConfirmed) {
            window.location.href = url;
          }
        });
      });
    });
  });
</script>

</html>