Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('cart',views.CartDetail.as_view(),name='Cart_datail'),
    path('cart/add/<int:pk>',views.CartAdd.as_view(),name='Cart_add')
]

Dashbord/urls.py
from django.urls import path
from . import views

app_name = 'Profile'

urlpatterns = [
    path('profile/view',views.UserProfile,name='Profile_View'),
    path('profile/address',views.AddressView.as_view(),name='Address'),
    path('profile/address/add',views.Address_Add.as_view(),name='Address_add'),
    path('profile/change',views.Change_profile,name='ChangeProfile'),
    path('profile/change/password',views.ChangePasswordView.as_view(),name='ChangePassword'),
    path('profile/notifications',views.NotificationList.as_view(),name='Notification'),
    path('profile/comment',views.CommentViews.as_view(),name='CommentViews'),
    path('profile/comment/delete/<int:comment_id>/',views.DeleteCommentView.as_view(),name='DeleteCommentView'),
    path('profile/favorite',views.FavoriteViews.as_view(),name='FavoriteViews'),
    
]
    

Products/urls.py
from django.urls import path,re_path
from .import views

# نام اپ کاربران
app_name="Product"

urlpatterns = [
   re_path(r'products/(?P<slug>[-\w]+)/details',views.ProductDetails.as_view(), name='Product_details'),
   path('',views.Product_View.as_view(), name='Product_view'),
   path('product/list',views.Product_list.as_view(), name='Product_list'),
   

]

Shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('Products.urls')),
    path('', include('Cart.urls')),
    path('', include('Dashbord.urls')),
    path('', include('core.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .import views

# نام اپ کاربران
app_name="account"

urlpatterns = [
   path('login',views.UserLogin.as_view(), name='Login-user'),
   path('register',views.UserRegister.as_view(), name='Register-user'),
   path('verify',views.CheckOtp.as_view(), name='Verify'),
   path('logout', views.logout_user, name='logout'),
]

core/urls.py
from django.urls import path
from .import views

# نام اپ کاربران
app_name="Core"

urlpatterns = [
   path('aboute',views.About_Me.as_view(), name='About_me'),
   path('contact',views.Contact_Us.as_view(), name='Contact_us'),
]
  

templates/includes/footer.html
{% load static %}

<footer class="pt-5 shadow-xl bg-white">
    <!-- SERVICES -->
    <div>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-y-5 gap-x-10 justify-items-center mb-10">
        <div class="flex justify-center items-center flex-col rounded-3xl w-32 h-24">
          <img class="w-20" src="{% static 'image/services/cash-on-delivery.svg' %}" alt="">
          <span class="text-sm opacity-80">
          پرداخت درب منزل
          </span>
        </div>
        <div class="flex justify-center items-center flex-col rounded-3xl w-32 h-24">
          <img class="w-20" src="{% static 'image/services/days-return.svg' %}" alt="">
          <span class="text-sm opacity-80">
            ضمانت بازگشت کالا
          </span>
        </div>
        <div class="flex justify-center items-center flex-col rounded-3xl w-32 h-24">
          <img class="w-20" src="{% static 'image/services/days-return.svg' %}" alt="">
          <span class="text-sm opacity-80">
            تحویل سریع
          </span>
        </div>
        <div class="flex justify-center items-center flex-col rounded-3xl w-32 h-24">
          <img class="w-20" src="{% static 'image/services/original-products.svg' %}" alt="">
          <span class="text-sm opacity-80">
            ضمانت اصل بودن
          </span>
        </div>
      </div>
    </div>
    <!-- MAIN -->
    <div>
      <a href="{% url 'Product:Product_view' %}" class="inline-block mb-4 mx-4 ">
        <img
          src="{{ site_settings.logo.url }}" width="80px" height="80px"
          style="border-radius: 100%"
          alt="logo"
        />
      </a>
    </div>
    <div class="mx-auto shadow-lg">
      <div class="flex flex-wrap">
        <div class="w-full px-4 sm:w-2/3 lg:w-4/12">
          <div class="mb-10 w-full">
            <p class="mb-2 opacity-80">
              {{ site_settings.title }}  
            </p>
            <p class="mb-7 opacity-60 text-sm">
                  {{ site_settings.text_about_us }}  
            </p>
            
          </div>
        </div>
          
        <div class="w-full px-4 sm:w-1/2 lg:w-3/12">
          <div class="mb-10 w-full">
            <h4 class="mb-2 opacity-80">لینک های مفید:</h4>
            <ul class="grid gap-y-2">
              <li>
                <a
                  href="{% url 'Product:Product_view' %}"
                  class="mb-2 text-sm hover:text-red-600 transition opacity-60 hover:opacity-100"
                >
                خانه
                </a>
              </li>
              <li>
                <a
                  href="{% url 'Core:About_me' %}"
                  class="mb-12 text-sm hover:text-red-600 transition opacity-60 hover:opacity-100"
                >
                  درباره ما
                </a>
              </li>
              <li>
                <a
                  href="{% url 'Cart:Cart_datail' %}"
                  class="mb-2 text-sm hover:text-red-600 transition opacity-60 hover:opacity-100"
                >
                  پیگیری سفارش
                </a>
              </li>
              <li>

              </li>
              <li>

              </li>
            </ul>
          </div>
        </div>
        <div class="w-full px-4 sm:w-1/2 lg:w-3/12">
          <div class="mb-10 w-full">
            <h4 class="mb-2 opacity-80">ارتباط با ما:</h4>
            <ul class="grid gap-y-2">
              <li>
                <div
                  class="mb-2 text-sm opacity-60"
                > آدرس:
              {{ site_settings.address}}
                </div>
              </li>
              <li>
                <div
                  class="mb-2 text-sm opacity-60"
                >شماره تلفن همراه:
               {{ site_settings.phone1}}
                </div>
              </li>
               <li>
                <div
                  class="mb-2 text-sm opacity-60"
                >شماره تلفن ثابت:
               {{ site_settings.phone2}}
                </div>
              </li>
              <li>
                <div
                  class="mb-2 text-sm opacity-60"
                >
                  ساعت پاسخگویی:8 الی 22
                </div>
              </li>
            </ul>
          </div>
        </div>
        <div class="w-full px-4 sm:w-1/2 lg:w-2/12">
          <div class="mb-10 w-full">
            <h4 class="mb-2 text-center opacity-80">شبکه های اجتماعی:</h4>
            <div class="mb-5 flex items-center justify-center">
              <a href="#" title="instagram" class="mr-1 flex h-12 w-12 items-center justify-center p-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#333333" viewBox="0 0 256 256"><path d="M128,80a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160ZM176,24H80A56.06,56.06,0,0,0,24,80v96a56.06,56.06,0,0,0,56,56h96a56.06,56.06,0,0,0,56-56V80A56.06,56.06,0,0,0,176,24Zm40,152a40,40,0,0,1-40,40H80a40,40,0,0,1-40-40V80A40,40,0,0,1,80,40h96a40,40,0,0,1,40,40ZM192,76a12,12,0,1,1-12-12A12,12,0,0,1,192,76Z"></path></svg>                </a>
              <a href="#" title="telegram" class="mr-1 flex h-12 w-12 items-center justify-center p-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#333333" viewBox="0 0 256 256"><path d="M236.88,26.19a9,9,0,0,0-9.16-1.57L25.06,103.93a14.22,14.22,0,0,0,2.43,27.21L80,141.45V200a15.92,15.92,0,0,0,10,14.83,15.91,15.91,0,0,0,17.51-3.73l25.32-26.26L173,220a15.88,15.88,0,0,0,10.51,4,16.3,16.3,0,0,0,5-.79,15.85,15.85,0,0,0,10.67-11.63L239.77,35A9,9,0,0,0,236.88,26.19Zm-61.14,36L86.15,126.35l-49.6-9.73ZM96,200V152.52l24.79,21.74Zm87.53,8L100.85,135.5l119-85.29Z"></path></svg>                </a>
              <a href="#" title="whatsapp" class="mr-1 flex h-12 w-12 items-center justify-center p-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#333333" viewBox="0 0 256 256"><path d="M187.58,144.84l-32-16a8,8,0,0,0-8,.5l-14.69,9.8a40.55,40.55,0,0,1-16-16l9.8-14.69a8,8,0,0,0,.5-8l-16-32A8,8,0,0,0,104,64a40,40,0,0,0-40,40,88.1,88.1,0,0,0,88,88,40,40,0,0,0,40-40A8,8,0,0,0,187.58,144.84ZM152,176a72.08,72.08,0,0,1-72-72A24,24,0,0,1,99.29,80.46l11.48,23L101,118a8,8,0,0,0-.73,7.51,56.47,56.47,0,0,0,30.15,30.15A8,8,0,0,0,138,155l14.61-9.74,23,11.48A24,24,0,0,1,152,176ZM128,24A104,104,0,0,0,36.18,176.88L24.83,210.93a16,16,0,0,0,20.24,20.24l34.05-11.35A104,104,0,1,0,128,24Zm0,192a87.87,87.87,0,0,1-44.06-11.81,8,8,0,0,0-6.54-.67L40,216,52.47,178.6a8,8,0,0,0-.66-6.54A88,88,0,1,1,128,216Z"></path></svg>                </a>
            </div>
            <div class="flex items-center justify-center gap-x-5">
              <a href="#">
                <img class="w-28 h-auto" src="{% static 'image/logoSecrets/symbol-02.png' %}" alt="">
              </a>
              <a href="#">
                <img class="w-20 h-auto" src="{% static 'image/logoSecrets/zarinPal.png' %}"  alt="">
              </a>
          </div>
        </div>
        <!-- COPYRIGHT -->
        <p class="mb-7 opacity-60 text-sm">
                 تمامی حقوق محفوظ است. | طراحی و کد نویسی: فناور هوشمند یزدان شهر ©
            </p>
      </div>
    </div>
     </div>
     
    <!-- COPYRIGHT -->
    {% comment %} </div>
    <div class="px-4 grid grid-cols-1 sm:grid-cols-2 border-t-[1px] py-5 text-gray-400">
      <span class="text-xs text-center sm:text-right">تمامی حقوق محفوظ است. | طراحی و کد نویسی: فناور هوشمند یزدان شهر ©
      </span>
  </div> {% endcomment %}
    </footer>

templates/includes/profile_navbar.html
{% load static %}
<div class="max-w-[1440px] mx-auto px-3">
  <div class="bg-white shadow-xl my-5 lg:my-10 rounded-xl md:rounded-2xl p-3 md:p-5">
    <div class="flex flex-col md:flex-row gap-5">
      <div class="md:w-4/12 lg:w-3/12 flex flex-col gap-y-5">
        <div class="border rounded-3xl shadow-lg flex flex-col justify-center items-center py-4 gap-y-5">

          {% if user.image %}
          <img class="border rounded-full w-24" src="{{ user.image.url }}" alt="">

          {% else %}
          <img class="border rounded-full w-24" src="{% static 'image/team-2.jpg' %}" alt="">

          {% endif %}

          <span class="font-semibold opacity-80">
            {{ request.user }}
          </span>

          <span class="flex text-xs opacity-70">
            <div>
              شماره تلفن:
            </div>

            <div>
              {{ request.user.phone }}
            </div>

          </span>
          <a href="{% url 'account:logout' %}"
            class="text-sm opacity-80 border-t w-full pt-2 flex justify-center flex-row-reverse items-center hover:text-red-600 transition">
            خروج از حساب
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M110,216a6,6,0,0,1-6,6H48a14,14,0,0,1-14-14V48A14,14,0,0,1,48,34h56a6,6,0,0,1,0,12H48a2,2,0,0,0-2,2V208a2,2,0,0,0,2,2h56A6,6,0,0,1,110,216Zm110.24-92.24-40-40a6,6,0,0,0-8.48,8.48L201.51,122H104a6,6,0,0,0,0,12h97.51l-29.75,29.76a6,6,0,1,0,8.48,8.48l40-40A6,6,0,0,0,220.24,123.76Z">
              </path>
            </svg>
          </a>
        </div>
        <div class="border rounded-3xl shadow-lg flex flex-col justify-center items-center p-2 gap-y-2">

          <a href="{% url 'Profile:Profile_View' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl
                    {% if request.resolver_match.url_name == 'Profile_View' %}
                      bg-gray-200 text-red-600 
                        {% endif %}">
            پروفایل
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M229.19,213c-15.81-27.32-40.63-46.49-69.47-54.62a70,70,0,1,0-63.44,0C67.44,166.5,42.62,185.67,26.81,213a6,6,0,1,0,10.38,6C56.4,185.81,90.34,166,128,166s71.6,19.81,90.81,53a6,6,0,1,0,10.38-6ZM70,96a58,58,0,1,1,58,58A58.07,58.07,0,0,1,70,96Z">
              </path>
            </svg>
          </a>

          <a href="./profile-order.html"
            class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl">
            سفارش ها
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M134,120v56a6,6,0,0,1-12,0V120a6,6,0,0,1,12,0ZM237.88,97.85,224,201.85A14,14,0,0,1,210.13,214H45.87A14,14,0,0,1,32,201.85l-13.87-104A14,14,0,0,1,32,82H69.28l54.2-61.95a6,6,0,0,1,9,0l54.2,62H224a14,14,0,0,1,13.87,15.85ZM85.22,82h85.56L128,33.11ZM225.5,94.68A2,2,0,0,0,224,94H32a2,2,0,0,0-1.51.68A2,2,0,0,0,30,96.26l13.86,104a2,2,0,0,0,2,1.73H210.13a2,2,0,0,0,2-1.73L226,96.26A1.93,1.93,0,0,0,225.5,94.68ZM181.4,114a6,6,0,0,0-6.57,5.37l-5.6,56A6,6,0,0,0,174.6,182l.61,0a6,6,0,0,0,6-5.4l5.6-56A6,6,0,0,0,181.4,114ZM81.17,119.4a6,6,0,0,0-11.94,1.2l5.6,56a6,6,0,0,0,6,5.4l.61,0a6,6,0,0,0,5.37-6.57Z">
              </path>
            </svg>
          </a>
          <a href="{% url 'Profile:FavoriteViews' %}"
            class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl
             {% if request.resolver_match.url_name == 'FavoriteViews' %}
                      bg-gray-200 text-red-600 
                        {% endif %}">
            علاقه مندی ها
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M178,34c-21,0-39.26,9.47-50,25.34C117.26,43.47,99,34,78,34A60.07,60.07,0,0,0,18,94c0,29.2,18.2,59.59,54.1,90.31a334.68,334.68,0,0,0,53.06,37,6,6,0,0,0,5.68,0,334.68,334.68,0,0,0,53.06-37C219.8,153.59,238,123.2,238,94A60.07,60.07,0,0,0,178,34ZM128,209.11C111.59,199.64,30,149.72,30,94A48.05,48.05,0,0,1,78,46c20.28,0,37.31,10.83,44.45,28.27a6,6,0,0,0,11.1,0C140.69,56.83,157.72,46,178,46a48.05,48.05,0,0,1,48,48C226,149.72,144.41,199.64,128,209.11Z">
              </path>
            </svg>
          </a>

          <a href="{% url 'Profile:Address' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl
                    {% if request.resolver_match.url_name == 'Address' or request.resolver_match.url_name == 'Address_add' %}
                      bg-gray-200 text-red-600 
                        {% endif %}">
            آدرس های من
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M128,66a38,38,0,1,0,38,38A38,38,0,0,0,128,66Zm0,64a26,26,0,1,1,26-26A26,26,0,0,1,128,130Zm0-112a86.1,86.1,0,0,0-86,86c0,30.91,14.34,63.74,41.47,94.94a252.32,252.32,0,0,0,41.09,38,6,6,0,0,0,6.88,0,252.32,252.32,0,0,0,41.09-38c27.13-31.2,41.47-64,41.47-94.94A86.1,86.1,0,0,0,128,18Zm0,206.51C113,212.93,54,163.62,54,104a74,74,0,0,1,148,0C202,163.62,143,212.93,128,224.51Z">
              </path>
            </svg>
          </a>

          <a href="{% url 'Profile:Notification' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center transition hover:bg-gray-100 py-3 rounded-2xl relative
          {% if request.resolver_match.url_name == 'Notification' %}
              bg-gray-200 text-red-600 
          {% endif %}">
            اعلان‌ها
            <!-- Notification Bell Icon -->
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
              stroke="#606060" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" class="ml-2">
              <path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9" />
              <path d="M13.73 21a2 2 0 0 1-3.46 0" />

              {% comment %} {% if notifications %}
              <circle cx="19" cy="5" r="3" fill="red" />
              {% endif %}
              {% endcomment %}

            </svg>
          </a>
          <a href="{% url 'Profile:CommentViews' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl
            {% if request.resolver_match.url_name == 'CommentViews' %}
              bg-gray-200 text-red-600 
              {% endif %}">
            نظرات من
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M138,128a10,10,0,1,1-10-10A10,10,0,0,1,138,128ZM84,118a10,10,0,1,0,10,10A10,10,0,0,0,84,118Zm88,0a10,10,0,1,0,10,10A10,10,0,0,0,172,118Zm58,10A102,102,0,0,1,79.31,217.65L44.44,229.27a14,14,0,0,1-17.71-17.71l11.62-34.87A102,102,0,1,1,230,128Zm-12,0A90,90,0,1,0,50.08,173.06a6,6,0,0,1,.5,4.91L38.12,215.35a2,2,0,0,0,2.53,2.53L78,205.42a6.2,6.2,0,0,1,1.9-.31,6.09,6.09,0,0,1,3,.81A90,90,0,0,0,218,128Z">
              </path>
            </svg>
          </a>
          <a href="{% url 'Profile:ChangeProfile' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center hover:text-red-600 transition hover:bg-gray-100 py-3 rounded-2xl
            {% if request.resolver_match.url_name == 'ChangeProfile' %}
                bg-gray-200 text-red-600 
                {% endif %}">
            ویرایش حساب
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#474747" viewBox="0 0 256 256">
              <path
                d="M142,176a6,6,0,0,1-6,6,14,14,0,0,1-14-14V128a2,2,0,0,0-2-2,6,6,0,0,1,0-12,14,14,0,0,1,14,14v40a2,2,0,0,0,2,2A6,6,0,0,1,142,176ZM124,94a10,10,0,1,0-10-10A10,10,0,0,0,124,94Zm106,34A102,102,0,1,1,128,26,102.12,102.12,0,0,1,230,128Zm-12,0a90,90,0,1,0-90,90A90.1,90.1,0,0,0,218,128Z">
              </path>
            </svg>
          </a>
          <a href="{% url 'Profile:ChangePassword' %}" class="text-sm opacity-80 w-full flex justify-end pr-5 flex-row-reverse items-center transition hover:bg-gray-100 py-3 rounded-2xl relative
            {% if request.resolver_match.url_name == 'ChangePassword' %}
                      bg-gray-200 text-red-600 
                        {% endif %}">
            تغییر رمز عبور
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
              stroke="#606060" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" class="ml-2">
              <rect x="3" y="11" width="18" height="10" rx="2" ry="2" />
              <path d="M7 11V7a5 5 0 0 1 10 0v4" />

            </svg>
          </a>
        </div>
      </div>