Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('cart',views.CartDetail.as_view(),name='Cart_datail'),
    path('cart/add/<int:pk>',views.CartAdd.as_view(),name='Cart_add')
]

Dashbord/urls.py
from django.urls import path
from . import views

app_name = 'Profile'

urlpatterns = [
    path('profile/view',views.UserProfile,name='Profile_View'),
    path('profile/address',views.AddressView.as_view(),name='Address'),
    path('profile/address/add',views.Address_Add.as_view(),name='Address_add'),
    path('profile/change',views.Change_profile,name='ChangeProfile'),
    path('profile/change/password',views.ChangePasswordView.as_view(),name='ChangePassword'),
    path('profile/notifications',views.NotificationList.as_view(),name='Notification'),
    path('profile/comment',views.CommentViews.as_view(),name='CommentViews'),
    path('profile/comment/delete/<int:comment_id>/',views.DeleteCommentView.as_view(),name='DeleteCommentView'),
    path('profile/favorite',views.FavoriteViews.as_view(),name='FavoriteViews'),
    
]
    

Products/urls.py
from django.urls import path,re_path
from .import views

# نام اپ کاربران
app_name="Product"

urlpatterns = [
   re_path(r'products/(?P<slug>[-\w]+)/details',views.ProductDetails.as_view(), name='Product_details'),
   path('',views.Product_View.as_view(), name='Product_view'),
   path('product/list',views.Product_list.as_view(), name='Product_list'),
   

]

Shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('Products.urls')),
    path('', include('Cart.urls')),
    path('', include('Dashbord.urls')),
    path('', include('core.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from account.models import User
from  django.utils.text import slugify
from django.utils.translation import gettext as _
from colorfield.fields import ColorField
from  django.utils.text import slugify


class ProductStatusType(models.IntegerChoices):
    publish = 1 ,("نمایش")
    draft = 2 ,("عدم نمایش")


class Category(models.Model):
    title = models.CharField(
        max_length=50,verbose_name="عنوان"
        )
    image = models.ImageField(
      verbose_name="تصویر دسته بندی",upload_to='category/image',null=True,blank=True
        )
    created = models.DateTimeField(
        auto_now_add=True,verbose_name="تاریخ ایجاد"
        )
    views = models.BooleanField(
        default=True,verbose_name='نمایش در صحفه اصلی '
    )
    slug = models.SlugField(
        verbose_name='نامک',help_text='مقدار به صورت خودکار از عنوان محصول استلفاده می شود',blank=True,unique=True
        )
    
    
    def save(self,force_insert=False,force_update=False,using=None,
             update_fields=None):
        self.slug = slugify(self.title,allow_unicode=True)
        super(Category, self).save()

   
    def __str__(self):
        return self.title

    def show_image(self):
        """To display images in the management panel"""
        if self.image:
            return format_html(f'<img src="{self.image.url}" width="78 px" height="50" />')
        return format_html('<h3 style="color: red">تصویر ندارد</h3>')
    show_image.short_description = " تصاویر"


    class Meta:
        verbose_name_plural = "دسته بندی ها"


class Size(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural ="سایز"


class Color(models.Model):
    title = models.CharField(
        max_length=30,verbose_name="عنوان رنگ", help_text='لطفا عنوان را خالی نگذارید',
        )
    color_code = ColorField(
        max_length=20, unique=True, default="#229605", help_text='این یک کد رنگی است', verbose_name='کد رنگ'
        )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='تاریخ ایجاد',null=True
        )

    def __str__(self):
      return f"{self.title} ({self.color_code})"

    class Meta:
        verbose_name_plural = "رنگ بندی "


class Brand(models.Model):
    title = models.CharField(
        max_length=60,verbose_name="برند",blank=True,null=True
        )

    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = "برند ها "


class Products(models.Model):
    title = models.CharField(
        max_length=80,verbose_name="عنوان"
        )
    hover_title = models.CharField(
        max_length=60,verbose_name="عنوان معرفی",blank=True,null=True
        )
    image = models.ImageField(
        upload_to="product/image",blank=True,null=True,verbose_name=" بارگذاری تصویر اصلی"
        )
    image_subset_1 = models.ImageField(
        upload_to="product/image",blank=True,null=True,verbose_name=" بارگذاری تصویر دوم"
        )
    image_subset_2 = models.ImageField(
        upload_to="product/image",blank=True,null=True,verbose_name="بارگذاری تصویر سوم "
        )
    image_subset_3 = models.ImageField(
        upload_to="product/image",blank=True,null=True,verbose_name=" بارگذاری تصویر چهارم"
        )
    price = models.DecimalField(
        verbose_name="قیمت",max_digits=10,decimal_places=0,
        )
    caption = models.TextField(
        verbose_name='درباره محصول'
        )
    category = models.ForeignKey(
    Category,on_delete=models.SET_NULL,null=True,blank=True,verbose_name="دسته بندی", related_name='products'
        )
    size = models.ManyToManyField(
        Size,blank=True,related_name='products',verbose_name="سایزها"
        )
    color = models.ManyToManyField(
        Color,related_name='products',verbose_name="رنگ بندی ها",blank=True
        )
    status = models.IntegerField(
        choices=ProductStatusType.choices,default=ProductStatusType.draft.value,verbose_name="وضعیت نمایش"
        )
    stock_count =models.IntegerField(
        verbose_name= " تعداد موجودی",null=True,blank=True
        )
    created = models.DateTimeField(
        auto_now_add=True,verbose_name= 'تاریخ ایجاد',null=True
        )
    views = models.IntegerField(
        default=0, editable=False, verbose_name='بازدید'
        )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name='تاریخ به‌روزرسانی'
        )
    # brand = models.ForeignKey(
    #     Brand,verbose_name='برند'
    # )
    slug = models.SlugField(
        verbose_name='نامک',help_text='مقدار به صورت خودکار از عنوان محصول استلفاده می شود',blank=True,unique=True
        )
    
    
    def save(self,force_insert=False,force_update=False,using=None,
             update_fields=None):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Products, self).save()

    def __str__(self):
        return self.title

    def show_image(self):
        """To display images in the management panel"""

        if self.image:
            return format_html(f'<img src="{self.image.url}" width="78 px" height="50" />')
        return format_html('<h3 style="color: red">تصویر ندارد</h3>')
    show_image.short_description = " تصاویر"

    class Meta:
        ordering = ['-created']
        verbose_name_plural = "محصولات"



class Information(models.Model):
    product = models.ForeignKey(
        Products,on_delete=models.CASCADE,related_name="information",verbose_name='محصول'
        )
    Feature_title = models.CharField(
        max_length=80,blank=True,null=True,verbose_name="عنوان ویژگی"
        )
    Featur = models.CharField(
        max_length=60,blank=True,null=True,verbose_name="ویژگی"
        )

    def __str__(self):
        return f"{self.product.title} - {self.Feature_title or ''}: {self.Featur or ''}"

    class Meta:
        verbose_name_plural = 'ویژگی ها'



class Comment(models.Model):
    """Implementation of the questions section,
    which features questions and answers after login"""
    
    STATUS = (
    ("Awaiting confirmation", "در انتظار تایید"),
    ("It was confirmed", "تایید شد"),
    ("rejected", "رد شد")
    )
    products = models.ForeignKey(
        Products, on_delete=models.CASCADE, related_name="comments",verbose_name="محصول"
        )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments",verbose_name="کاربر"
        )
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="replies", null=True,blank=True,verbose_name="پاسخ ها "
        )
    body = models.TextField(
        verbose_name="نظر"
        )
    created_at =models.DateTimeField(
        auto_now_add=True,verbose_name="تاریخ ایجاد"
        )
    status = models.CharField(
        choices=STATUS, max_length=30, default='Awaiting confirmation', verbose_name='وضعیت'
        )

    def __str__(self):
        return self.products.title
    class Meta:
        verbose_name_plural = 'نظرات'

Products/views.py
from django.contrib import messages
from urllib import request
from django.shortcuts import render
from django.views.generic import DetailView,ListView
from Products.models import Products,Comment,Color, ProductStatusType,Category
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404,render,redirect


class ProductDetails(DetailView):
    template_name = "Product/single-product.html"
    model = Products
    context_object_name = 'products'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['colors'] = product.color.all() 
        return context
    
    def post(self, request, pk):
        
     if request.user.is_authenticated:
        self.object = self.get_object()
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        
        if body:
         Comment.objects.create(
        body=body,
        products=self.object,
        user=request.user,
        parent_id=parent_id
    )
        else:
          messages.error(request, "متن نظر نمی‌تواند خالی باشد.")
        return redirect(request.path)
    

class Product_View(ListView):
    model = Products
    template_name = "Product/index.html"
    context_object_name = 'Products'
    queryset = Products.objects.filter(
        status=ProductStatusType.publish.value)
    paginate_by = 8


class Product_list(ListView):
    model = Products
    template_name = "Product/list_view.html"
    paginate_by = 2
    
    def get_queryset(self):
        queryset = Products.objects.filter(
        status=ProductStatusType.publish.value)
        if search_q:=self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)    
        if category_id:=self.request.GET.getlist("category_id"):
            queryset = queryset.filter(category__id__in=category_id).distinct()
        return queryset
    
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["categories"] = Category.objects.all()
       context["selected_categories"] = self.request.GET.getlist("category_id")
       return context
   
        
    
    
    

Products/templates/Product/index.html
{% load static %}
{% load jalali_tags %}
{% load filters %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="theme-color" content="#b91c1c" />

  <link rel="stylesheet" href="{% static 'css/output.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}">

  <!-- SLIDER HERO -->
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
  <!-- PRODUCT SLIDER CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.product.slider.css' %}" />

  <title>صفحه اصلی</title>
</head>

<body class="bg-gray-50">

  <!-- NAVBAR -->
  <div>
    <!-- TOP -->
    {% include 'includes/head.html' %}
    <!-- OPACITY SCREEN FOR SEARCH INPUT FOCUS -->

    <div class="absolute w-full h-screen bg-gray-200 opacity-40 z-40 hidden" id="opacitiScreen" onclick="closeScreen()">
    </div>
  </div>
  <!-- BOTTOM NAVIGATION -->
  <div class="px-4 bg-white shadow-2xl w-full border fixed bottom-0 left-1/2 -translate-x-1/2 md:hidden z-50">
    <div class="grid grid-cols-5">
      <div class="flex-1 group">
       <a href="{% url 'Profile:Profile_View' %}" 
   class="flex items-end justify-center text-center mx-auto pt-2 w-full 
          group 
          text-gray-800 hover:text-red-500
          {% if request.resolver_match.url_name == 'Profile_View' %} text-red-500 {% endif %}">
          
          <span class="block pt-1 pb-1">
            <svg class="mx-auto fill-gray-800 group-hover:fill-red-600 
            {% if request.resolver_match.url_name == 'Profile_View' %} fill-red-600 {% endif %}
            " xmlns="http://www.w3.org/2000/svg" width="22"
              height="22" fill="" viewBox="0 0 256 256">
              <path
                d="M230.92,212c-15.23-26.33-38.7-45.21-66.09-54.16a72,72,0,1,0-73.66,0C63.78,166.78,40.31,185.66,25.08,212a8,8,0,1,0,13.85,8c18.84-32.56,52.14-52,89.07-52s70.23,19.44,89.07,52a8,8,0,1,0,13.85-8ZM72,96a56,56,0,1,1,56,56A56.06,56.06,0,0,1,72,96Z">
              </path>
            </svg>
            <span class="block text-xs py-1">پروفایل</span>
            <span class="block w-5 mx-auto h-1 group-hover:bg-red-500 rounded-full
             {% if request.resolver_match.url_name == 'Profile_View' %} bg-red-500 {% endif %}">
            </span>
          </span>
        </a>
      </div>
      <div class="flex-1 group">
        <a href="#"
          class="flex items-end justify-center text-center mx-auto pt-2 w-full text-gray-800 group-hover:text-red-500">
          <span class="block pt-1 pb-1">
            <svg class="mx-auto fill-gray-800 group-hover:fill-red-600" xmlns="http://www.w3.org/2000/svg" width="22"
              height="22" fill="#000000" viewBox="0 0 256 256">
              <path
                d="M178,32c-20.65,0-38.73,8.88-50,23.89C116.73,40.88,98.65,32,78,32A62.07,62.07,0,0,0,16,94c0,70,103.79,126.66,108.21,129a8,8,0,0,0,7.58,0C136.21,220.66,240,164,240,94A62.07,62.07,0,0,0,178,32ZM128,206.8C109.74,196.16,32,147.69,32,94A46.06,46.06,0,0,1,78,48c19.45,0,35.78,10.36,42.6,27a8,8,0,0,0,14.8,0c6.82-16.67,23.15-27,42.6-27a46.06,46.06,0,0,1,46,46C224,147.61,146.24,196.15,128,206.8Z">
              </path>
            </svg>
            <span class="block text-xs py-1">علاقه مندی</span>
            <span class="block w-5 mx-auto h-1 group-hover:bg-red-500 rounded-full"></span>
          </span>
        </a>
      </div>
      <div class="flex-1 group">
        <a href="#" class="flex items-end justify-center text-center mx-auto pt-2 w-full text-red-500">
          <span class="block pt-1 pb-1">
            <svg class="mx-auto fill-red-600" xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#000000"
              viewBox="0 0 256 256">
              <path
                d="M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z">
              </path>
            </svg>
            <span class="block text-xs py-1">صفحه اصلی</span>
            <span class="block w-5 mx-auto h-1 bg-red-500 rounded-full"></span>
          </span>
        </a>
      </div>
      <div class="flex-1 group">
        <a href="#"
          class="flex items-end justify-center text-center mx-auto pt-2 w-full text-gray-800 group-hover:text-red-500">
          <span class="block pt-1 pb-1">
            <svg class="mx-auto fill-gray-800 group-hover:fill-red-600" xmlns="http://www.w3.org/2000/svg" width="22"
              height="22" fill="#000000" viewBox="0 0 256 256">
              <path
                d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z">
              </path>
            </svg>
            <span class="block text-xs py-1">جستجو</span>
            <span class="block w-5 mx-auto h-1 group-hover:bg-red-500 rounded-full"></span>
          </span>
        </a>
      </div>
      <div class="flex-1 group">
        <a href="#"
          class="flex items-end justify-center text-center mx-auto pt-2 w-full text-gray-800 group-hover:text-red-500">
          <span class="block pt-1 pb-1">
            <svg class="mx-auto fill-gray-800 group-hover:fill-red-600" xmlns="http://www.w3.org/2000/svg" width="22"
              height="22" fill="#000000" viewBox="0 0 256 256">
              <path
                d="M222.14,58.87A8,8,0,0,0,216,56H54.68L49.79,29.14A16,16,0,0,0,34.05,16H16a8,8,0,0,0,0,16h18L59.56,172.29a24,24,0,0,0,5.33,11.27,28,28,0,1,0,44.4,8.44h45.42A27.75,27.75,0,0,0,152,204a28,28,0,1,0,28-28H83.17a8,8,0,0,1-7.87-6.57L72.13,152h116a24,24,0,0,0,23.61-19.71l12.16-66.86A8,8,0,0,0,222.14,58.87ZM96,204a12,12,0,1,1-12-12A12,12,0,0,1,96,204Zm96,0a12,12,0,1,1-12-12A12,12,0,0,1,192,204Zm4-74.57A8,8,0,0,1,188.1,136H69.22L57.59,72H206.41Z">
              </path>
            </svg>
            <span class="block text-xs py-1">سبد خرید</span>
            <span class="block w-5 mx-auto h-1 group-hover:bg-red-500 rounded-full"></span>
          </span>
        </a>
      </div>
    </div>
  </div>

  <!-- HERO SLIDER -->

  <div class="md:w-[100%] mx-auto md:mt-5 hidden md:block">
    <div dir="ltr" class="owl-carousel">

      {% for banner in Banners %}
      <div class="box-border">

        <img class="rounded-md md:rounded-3xl md:px- box-border" src="{{ banner.image.url }}"
          alt="{{ banner.title }}" />

      </div>
      {% endfor %}

    </div>
  </div>
  </div>

  <!-- HERO SLIDER MOBILE -->

  <div class="md:w-[100%] mx-auto md:mt-5 md:hidden">
    <div dir="ltr" class="owl-carousel">

      {% for banner in Banners %}
      <div class="box-border">
        <img class="rounded-md md:rounded-3xl md:px-2 box-border" src="{{ banner.image.url }}"
          alt="{{ banner.title }}" />
      </div>
      {% endfor %}

      </a>
    </div>
  </div>
  </div>

  <!--CATEGORYS -->
  <div class="bg-white rounded-2xl py-6 shadow-xl my-10">
    <div class="flex justify-between px-5 pb-5 md:px-10 items-center">
      <div class="border-b-2 border-red-500 pb-1">دسته بندی ها </div>
      <a href="{% url 'Product:Product_list' %}">
        <div class="transition px-4 py-2 rounded-xl flex justify-center items-center text-red-500 hover:text-red-600">
          دیدن همه<img class="w-4" src="{% static 'image/arrow-left.png' %}" alt=""></div>
      </a>
    </div>
    <div
      class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-7 gap-x-4 gap-y-4 md:gap-x-8 2xl:gap-x-10 px-3 md:px-8 lg:px-28">

      {% for Category in Categories %}
      <a href="{% url 'Product:Product_list' %}" class="flex justify-center items-center flex-col gap-y-3 hover:scale-105 transition">
        <img src="{{ Category.image.url }}" width="160px" height="200px" style="border-radius: 50%"
          alt="{{ Category.title }}">
        <div class="text-sm opacity-90">{{ Category.title }}</div>
        {% endfor %}

      </a>
    </div>
  </div>

  <!-- PRODUCT SLIDER 2 -->
  <div class="bg-white rounded-2xl pt-10 shadow-xl my-10">
    <!-- TOP SLIDER -->
    {% for Category in Categories %}
    <div class="flex justify-between px-5 md:px-10 items-center">
      <div class="border-b-2 border-red-500 pb-1">{{ Category.title }}</div>
      <a href="{% url 'Product:Product_list' %}">
        <div class="transition px-4 py-2 rounded-xl flex justify-center items-center text-red-500 hover:text-red-600">
          دیدن همه<img class="w-4" src="{% static ' image/arrow-left.png' %}" alt=""></div>
      </a>
    </div>

    <!-- SLIDER -->
    <div class="containerPSlider swiper">
      <div class="slide-container1 px-2">
        <div class="card-wrapper swiper-wrapper py-4">

          {% for Product in Category.products.all %}

          <a href="{% url 'Product:Product_details' slug=Product.slug %}" class="card swiper-slide my-2 p-2 md:p-3 ">
            <div class="image-box mb-6 ">
              <div>
                {% if Product.image %}
                <img class="hover:scale-105 transition rounded-3xl w-full mx-auto" src="{{ Product.image.url }}"
                  alt="{{ Product.title }}" />
                {% else %}
                <img class="hover:scale-105 transition rounded-3xl w-full mx-auto" src="{% static 'image/logo.png' %}"
                  alt="{{ Product.title }}" />
                {% endif %}
              </div>

            </div>
            <div class="space-y-3 text-center">
              <span class="text-sm opacity-80 mb-2 h-8 md:h-10">
                <div>
                  {{ Product.title }}
                </div>
              </span>
              <div class="flex justify-center mt-1 mb-2 text-sm">
                <div>{{ Product.price|rial_price }}</div>
              </div>
            </div>
          </a>

          {% endfor %}

          <div class="image-box mb-6 ">
            <div>
              <img class="hover:scale-105 transition rounded-3xl w-full mx-auto" src="" alt="" />
            </div>
          </div>
          <div class="space-y-3 text-center">
            <span class="text-sm opacity-80 mb-2 h-8 md:h-10">
          </div>
        </div>
        <div class="swiper-button-next swiper-navBtn">
        </div>
        <div class="swiper-button-prev swiper-navBtn">
        </div>
        <div class="bg-white rounded-2xl pt-10 shadow-xl my-10"></div>
      </div>
    </div>
    {% endfor %}

    <!-- FOOTER -->
    {% include 'includes/footer.html' %}

</body>
<!--DROPDOWNS FOR NAVBAR-->
<script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer>
</script>
<!--MOBILE NAVBAR-->
<script src="{% static 'js/navbar.js' %}"></script>
<!-- SHOW MODAL SEARCH -->
<script src="{% static 'js/searchBox.js' %}"></script>
<!-- SLIDER HERO -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/sliderHero.js' %}"></script>
<!-- PRODUCT SLIDER -->
<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'js/scriptSlider.style.js' %}"></script>
<!-- BIG SLIDER -->
<script src="{% static 'js/bigSlider.js' %}"></script>
<!-- FOR TIMER OFF -->
<script src="{% static 'js/main.js' %}"></script>

</html>